### PR TITLE
GPII-1791:  Updated to "self-deduping" `gpii-express`...

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-1791](https://issues.gpii.net/browse/GPII-1791) for details.

### CODE REVIEW

**Comment by amb26** [comment]
i) tests hang immediately: 14:49:22.076:  Express started...
14:49:27.005:  Test case listener has not responded after 5000ms - at sequence pos 2 of 9 sequence element {
    "listener": "fluid.identity",
    "event": "{testEnvironment}.events.onFixturesConstructed"
} of fixture firefox: Confirm that query data is relayed on startup...

ii) Should add root *.json to jsonlint rules

**Comment by the-t-in-rtf** [comment]
The tests run on a clean checkout in Windows 10 with Firefox 47.0.1.  While I was on the "about" menu the update check kicked in.  I updated to 48.0, and now I see the same problem.  I will work on this, as it will affect every project that uses gpii-webdriver.

For now, you should be able to run the tests by setting the BROWSERS environment variable to "chrome".

I added the root JSON content to the lint checks.

**Comment by the-t-in-rtf** [comment]
I just updated to 48.0 on the Mac, same problem.  Working on it.

**Comment by the-t-in-rtf** [comment]
I updated to the latest `gpii-webdriver`, which only runs the tests in chrome.  This should allow the review to continue.

The one thing I know needs to be addressed is code coverage.  We don't currently have a working approach to generating proper code coverage reports for this package, which is the only one that can only be tested with gpii-webdriver.  I will give it some thought, likely I would use an approach similar to what I did with gpii-binder, which involved:
1. Instrumenting the code in a pretest script hook.
2. Firing up a server to listen for instrumentation results.
3. Adding a script on the client-side to pass along coverage reports.
4. Calling a script after test completion to collate the coverage reports.

**Comment by the-t-in-rtf** [comment]
Although it is certainly safe to review, this should not be merged/published until the following dependencies have been merged/published:
- [gpii-binder](https://github.com/GPII/gpii-binder/pull/3)
- [gpii-express](https://github.com/GPII/gpii-express/pull/25)
- [gpii-webdriver](https://github.com/GPII/gpii-webdriver/pull/1)

**Comment by amb26** [comment]
Currently I get:

```
15:34:49.733:  Successfully queued test firefox: Confirm that state changes are relayed...
15:34:49.876:  Express server listening on port 6984
15:34:49.876:  Express started...
15:34:54.787:  Test case listener has not responded after 5000ms - at sequence pos 2 of 9 sequence element {
    "listener": "fluid.identity",
    "event": "{testEnvironment}.events.onFixturesConstructed"
} of fixture firefox: Confirm that query data is relayed on startup...
```

**Comment by the-t-in-rtf** [comment]
Ah, that's just a config change that's needed to prevent FF tests from trying to run until gpii-webdriver supports it again.  Just a minute.

**Comment by amb26** [comment]
Ok cool - I get the following error on every test run under Chrome but they all complete successfully:

[0414/163437.736:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

**Comment by the-t-in-rtf** [comment]
Thanks for the merge.  I'll cut the release and write up the release notes shortly.  @amb26, for the record, what version of Chrome are you running on your machine?  I'd like to confirm the problem with gpii-webdriver and/or this package and write it up as a separate bug.

**Pull request merged**
