### PR TITLE
GPII-3922: May 2019 security updates and updated linting.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-3922](https://issues.gpii.net/browse/GPII-3922) for details.

### CODE REVIEW

**Comment by amb26** [comment]
Consistent hang on Windows in with the browser tests in Chrome:
````
DevTools listening on ws://127.0.0.1:12972/devtools/browser/2c6caf6b-5f6c-47c8-bb64-013cb0469fcc
12:53:17.926:  Test case listener has not responded after 5000ms - at sequence pos 5 of 17 sequence element {
    "event": "{testEnvironment}.webdriver.events.onExecuteScriptComplete",
    "listener": "{testEnvironment}.webdriver.executeScript",
    "args": [
        { Function

        },
        "fluid.getGlobalValue",
        "locationBarComponent.model.number"
    ]
} of fixture chrome: Confirm that backward and forward navigation work within a single page...
````

Some time after the timeout I then get a bizarrely worded message written by the characteristic schizoid nerd who writes these kinds of things assuming that we even know which "Program" he is talking about:
````
******** ERROR ********************************************************
This program is improperly using Base::Config by not initializing config
with the Load functions
See the documentation in Base/Dev/index.html for usage instructions.
At the minimum, LoadCommandLine should be use with a dummy command line
consisting of the program name.
************************************************************************
````

**Comment by the-t-in-rtf** [comment]
Thanks, @amb26.  I can see various problems in a Windows Vagrant VM, will troubleshoot and let you know when this is ready for further review.  At a minimum, this needs to be updated to use `nyc` instead of `istanbul`, and likely the test environment can be simplified, I'm not really even sure why express is necessary.

**Comment by the-t-in-rtf** [comment]
@amb26, I have updated the tests to use updated dependencies and a more modern take on instrumentation/coverage.  As a bonus, the coverage reports are now actually meaningful.

**Comment by amb26** [comment]
I now get coverage data, but the failure and output is as before - the test hangs during the "forward and backward navigation" test and the Chrome automation window stays open. Next, the coverage data appears, and then finally the schizoid message is output

**Comment by the-t-in-rtf** [comment]
Thanks, @amb26, I have cut the release and updated the infusion-docs pull to use the new version.  As we've discussed in chat, there may indeed be issues with particular combinations of chromedriver and Chrome, but it does work in the Vagrant Windows 10 VM.  Once we have CI for this and other repos that use gpii-webdriver, we will at least have a good sense of whether the latest versions in chocolatey work.

**Pull request merged**
